[API_KEYS]
GEMINI_API_KEY = "AIzaSyDP-07BYrtMlnCR3YCW-TfziB4kJGQzmKY"
jb_app_token = "U2FsdGVkX18NoB5PqRrGNuOugBT/3MWHiU3fWwdoHHV6XIJHxcX0QN6199COl6pnkUzLnU2z7MLhwO64cD5PVaf5SNPMUTyCQu1hhloa+PLGGo9dRpLv9tWp/xN744kST4MZM32pijJK106erd/KMD7Xj7kf1i+ZwxcikyMN1oUB0wKtlA1hKYyanxb5gaUOcZqeeyyLqxuXQVGePJ9SmJ2FJvJjOqih9F0hp/sWFkM="

SUBJECTS = ["computer science", "mathematics", "physics", "AI"]